name: workflow1
on:
  workflow_dispatch:
#  push:
#    branches: [main]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say normal hello
        run: echo "Hello user"
      - name: Say Hello
        run: echo "Hello $USER" 
      - name: say hello to user
        run: echo "Hello ${{ github.actor }}"      
  details:
    # needs works like depends on tag
    needs: greet
    runs-on: ubuntu-latest
    steps:
      - name: check docker and python details
        run:  docker --version && python --version
        
