name: workflow1
on:
  push:
    branches: [main]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say normal hello
        run: echo "Hello user"
      - name: Say Hello
        run: echo "Hello $USER" 
      - name: say hello to user
        run: echo "Hello ${{ github.actor }}"      
  details:
    runs-on: ubuntu-latest
      steps:
        - name: check docker and python details
          run:  docker --version && python --version
        
